
#ifndef OCTAFONT_BOLD8_H_
#define OCTAFONT_BOLD8_H_

#include "pixelfont.h"

class Octafont_bold8: public PixelFont {

private:
    static const bool chars[];
    static const int jumps[];
    static const int widths[];
    static const int height = 8;

    const bool *get_chars() override {
        return chars;
    }

    const int* get_jumps() override {
        return jumps;
    }

    const int* get_widths() override {
        return widths;
    }
    
    int get_font_height() override {
        return height;
    }
};

#define x true
#define o false
const bool Octafont_bold8::chars[] = {
/*   */
o, o, o, o,
o, o, o, o,
o, o, o, o,
o, o, o, o,
o, o, o, o,
o, o, o, o,
o, o, o, o,
o, o, o, o, 
/* ! */
x, x,
x, x,
x, x,
x, x,
x, x,
o, o,
x, x,
o, o, 
/* " */
x, x, o, x, x,
x, x, o, x, x,
x, x, o, x, x,
o, o, o, o, o,
o, o, o, o, o,
o, o, o, o, o,
o, o, o, o, o,
o, o, o, o, o, 
/* # */
o, o, x, x, o, o, x, x,
o, x, x, o, o, x, x, o,
x, x, x, x, x, x, x, x,
o, x, x, o, o, x, x, o,
x, x, x, x, x, x, x, x,
o, x, x, o, o, x, x, o,
x, x, o, o, x, x, o, o,
o, o, o, o, o, o, o, o, 
/* $ */
o, o, o, x, x, o, o, o,
o, x, x, x, x, x, x, o,
x, x, o, x, x, o, o, o,
o, x, x, x, x, x, x, o,
o, o, o, x, x, o, x, x,
o, x, x, x, x, x, x, o,
o, o, o, x, x, o, o, o,
o, o, o, o, o, o, o, o, 
/* % */
o, x, x, o, o, o, o, x, x, o,
x, o, o, x, o, o, x, x, o, o,
o, x, x, o, o, x, x, o, o, o,
o, o, o, o, x, x, o, o, o, o,
o, o, o, x, x, o, o, x, x, o,
o, o, x, x, o, o, x, o, o, x,
o, x, x, o, o, o, o, x, x, o,
o, o, o, o, o, o, o, o, o, o, 
/* & */
o, x, x, x, o, o,
x, x, o, x, x, o,
x, x, o, x, x, o,
o, x, x, x, x, x,
x, x, o, x, x, o,
x, x, o, x, x, x,
o, x, x, x, o, x,
o, o, o, o, o, o, 
/* ' */
x, x,
x, x,
x, x,
o, o,
o, o,
o, o,
o, o,
o, o, 
/* ( */
o, o, x, x,
o, x, x, o,
x, x, o, o,
x, x, o, o,
x, x, o, o,
o, x, x, o,
o, o, x, x,
o, o, o, o, 
/* ) */
x, x, o, o,
o, x, x, o,
o, o, x, x,
o, o, x, x,
o, o, x, x,
o, x, x, o,
x, x, o, o,
o, o, o, o, 
/* * */
o, o, o, o, o, o, o,
x, x, o, x, o, x, x,
x, x, o, x, o, x, x,
o, x, x, x, x, x, o,
o, x, x, x, x, x, o,
x, x, o, x, o, x, x,
x, x, o, x, o, x, x,
o, o, o, o, o, o, o, 
/* + */
o, o, o, o, o, o,
o, o, x, x, o, o,
o, o, x, x, o, o,
x, x, x, x, x, x,
o, o, x, x, o, o,
o, o, x, x, o, o,
o, o, o, o, o, o,
o, o, o, o, o, o, 
/* , */
o, o,
o, o,
o, o,
o, o,
o, o,
o, x,
x, x,
x, o, 
/* - */
o, o, o,
o, o, o,
o, o, o,
x, x, x,
x, x, x,
o, o, o,
o, o, o,
o, o, o, 
/* . */
o, o,
o, o,
o, o,
o, o,
o, o,
x, x,
x, x,
o, o, 
/* / */
o, o, o, x,
o, o, x, x,
o, o, x, x,
o, x, x, o,
x, x, o, o,
x, x, o, o,
x, o, o, o,
o, o, o, o, 
/* 0 */
o, x, x, x, x, o,
x, x, o, o, x, x,
x, x, o, x, x, x,
x, x, x, x, x, x,
x, x, x, o, x, x,
x, x, o, o, x, x,
o, x, x, x, x, o,
o, o, o, o, o, o, 
/* 1 */
o, x, x,
x, x, x,
o, x, x,
o, x, x,
o, x, x,
o, x, x,
o, x, x,
o, o, o, 
/* 2 */
o, x, x, x, x, o,
x, x, o, o, x, x,
o, o, o, x, x, x,
o, o, x, x, x, o,
o, x, x, x, o, o,
x, x, x, o, o, o,
x, x, x, x, x, x,
o, o, o, o, o, o, 
/* 3 */
o, x, x, x, o,
x, x, o, x, x,
o, o, o, x, x,
o, x, x, x, o,
o, o, o, x, x,
x, x, o, x, x,
o, x, x, x, o,
o, o, o, o, o, 
/* 4 */
o, o, x, x, x, o,
o, x, x, x, o, o,
x, x, x, o, o, o,
x, x, o, o, o, o,
x, x, o, x, x, o,
x, x, x, x, x, x,
o, o, o, x, x, o,
o, o, o, o, o, o, 
/* 5 */
x, x, x, x, x,
x, x, o, o, o,
x, x, o, o, o,
x, x, x, x, o,
o, o, o, x, x,
o, o, o, x, x,
x, x, x, x, o,
o, o, o, o, o, 
/* 6 */
o, x, x, x, o,
x, x, o, x, x,
x, x, o, o, o,
x, x, x, x, o,
x, x, o, x, x,
x, x, o, x, x,
o, x, x, x, o,
o, o, o, o, o, 
/* 7 */
x, x, x, x, x, x,
o, o, o, o, x, x,
o, o, o, x, x, o,
o, o, x, x, o, o,
o, x, x, o, o, o,
o, x, x, o, o, o,
o, x, x, o, o, o,
o, o, o, o, o, o, 
/* 8 */
o, x, x, x, x, o,
x, x, o, o, x, x,
x, x, o, o, x, x,
o, x, x, x, x, o,
x, x, o, o, x, x,
x, x, o, o, x, x,
o, x, x, x, x, o,
o, o, o, o, o, o, 
/* 9 */
o, x, x, x, o,
x, x, o, x, x,
x, x, o, x, x,
o, x, x, x, x,
o, o, o, x, x,
x, x, o, x, x,
o, x, x, x, o,
o, o, o, o, o, 
/* : */
o, o,
o, o,
x, x,
x, x,
o, o,
x, x,
x, x,
o, o, 
/* ; */
o, o,
o, o,
x, x,
x, x,
o, o,
o, x,
x, x,
x, o, 
/* < */
o, o, o, o,
o, o, o, o,
o, o, x, x,
o, x, x, o,
x, x, o, o,
o, x, x, o,
o, o, x, x,
o, o, o, o, 
/* = */
o, o, o, o,
o, o, o, o,
x, x, x, x,
x, x, x, x,
o, o, o, o,
x, x, x, x,
x, x, x, x,
o, o, o, o, 
/* > */
o, o, o, o,
o, o, o, o,
x, x, o, o,
o, x, x, o,
o, o, x, x,
o, x, x, o,
x, x, o, o,
o, o, o, o, 
/* ? */
o, x, x, x, o,
x, x, o, x, x,
o, o, o, x, x,
o, o, x, x, o,
o, x, x, o, o,
o, o, o, o, o,
o, x, x, o, o,
o, o, o, o, o, 
/* @ */
o, o, x, x, x, x, x, o,
o, x, x, o, o, o, x, x,
x, x, o, o, x, x, x, x,
x, x, o, x, x, o, x, x,
x, x, o, o, x, x, x, x,
o, x, x, o, o, o, o, o,
o, o, x, x, x, x, x, o,
o, o, o, o, o, o, o, o, 
/* A */
o, o, x, x, x, o, o,
o, x, x, o, x, x, o,
x, x, o, o, o, x, x,
x, x, o, o, o, x, x,
x, x, x, x, x, x, x,
x, x, o, o, o, x, x,
x, x, o, o, o, x, x,
o, o, o, o, o, o, o, 
/* B */
x, x, x, x, x, o,
x, x, o, o, x, x,
x, x, o, o, x, x,
x, x, x, x, x, o,
x, x, o, o, x, x,
x, x, o, o, x, x,
x, x, x, x, x, o,
o, o, o, o, o, o, 
/* C */
o, x, x, x, x,
x, x, x, o, o,
x, x, o, o, o,
x, x, o, o, o,
x, x, o, o, o,
x, x, x, o, o,
o, x, x, x, x,
o, o, o, o, o, 
/* D */
x, x, x, x, o,
x, x, o, x, x,
x, x, o, x, x,
x, x, o, x, x,
x, x, o, x, x,
x, x, o, x, x,
x, x, x, x, o,
o, o, o, o, o, 
/* E */
x, x, x, x, x,
x, x, o, o, o,
x, x, o, o, o,
x, x, x, x, o,
x, x, o, o, o,
x, x, o, o, o,
x, x, x, x, x,
o, o, o, o, o, 
/* F */
x, x, x, x, x,
x, x, o, o, o,
x, x, o, o, o,
x, x, x, x, o,
x, x, o, o, o,
x, x, o, o, o,
x, x, o, o, o,
o, o, o, o, o, 
/* G */
o, x, x, x, o,
x, x, o, o, o,
x, x, o, o, o,
x, x, o, x, x,
x, x, o, x, x,
x, x, o, o, x,
o, x, x, x, o,
o, o, o, o, o, 
/* H */
x, x, o, o, x, x,
x, x, o, o, x, x,
x, x, o, o, x, x,
x, x, x, x, x, x,
x, x, o, o, x, x,
x, x, o, o, x, x,
x, x, o, o, x, x,
o, o, o, o, o, o, 
/* I */
x, x,
x, x,
x, x,
x, x,
x, x,
x, x,
x, x,
o, o, 
/* J */
x, x, x, x, x,
o, o, o, x, x,
o, o, o, x, x,
o, o, o, x, x,
o, o, o, x, x,
x, o, o, x, x,
o, x, x, x, o,
o, o, o, o, o, 
/* K */
x, x, o, o, x, x,
x, x, o, x, x, x,
x, x, x, x, x, o,
x, x, x, x, o, o,
x, x, x, x, x, o,
x, x, o, x, x, x,
x, x, o, o, x, x,
o, o, o, o, o, o, 
/* L */
x, x, o, o, o,
x, x, o, o, o,
x, x, o, o, o,
x, x, o, o, o,
x, x, o, o, o,
x, x, o, o, o,
x, x, x, x, x,
o, o, o, o, o, 
/* M */
x, x, o, o, o, x, x,
x, x, x, o, x, x, x,
x, x, x, x, x, x, x,
x, x, o, x, o, x, x,
x, x, o, o, o, x, x,
x, x, o, o, o, x, x,
x, x, o, o, o, x, x,
o, o, o, o, o, o, o, 
/* N */
x, x, o, o, o, x, x,
x, x, x, o, o, x, x,
x, x, x, x, o, x, x,
x, x, o, x, x, x, x,
x, x, o, o, x, x, x,
x, x, o, o, o, x, x,
x, x, o, o, o, x, x,
o, o, o, o, o, o, o, 
/* O */
o, x, x, x, x, o,
x, x, o, o, x, x,
x, x, o, o, x, x,
x, x, o, o, x, x,
x, x, o, o, x, x,
x, x, o, o, x, x,
o, x, x, x, x, o,
o, o, o, o, o, o, 
/* P */
x, x, x, x, x, o,
x, x, o, o, x, x,
x, x, o, o, x, x,
x, x, x, x, x, o,
x, x, o, o, o, o,
x, x, o, o, o, o,
x, x, o, o, o, o,
o, o, o, o, o, o, 
/* Q */
o, x, x, x, x, o, o,
x, x, o, o, x, x, o,
x, x, o, o, x, x, o,
x, x, o, o, x, x, o,
x, x, o, o, x, x, o,
x, x, o, o, x, x, o,
o, x, x, x, x, x, x,
o, o, o, o, o, o, o, 
/* R */
x, x, x, x, x, o,
x, x, o, o, x, x,
x, x, o, o, x, x,
x, x, x, x, x, o,
x, x, x, x, o, o,
x, x, o, x, x, o,
x, x, o, o, x, x,
o, o, o, o, o, o, 
/* S */
o, x, x, x, x, o,
x, x, o, o, x, x,
x, x, x, o, o, o,
o, x, x, x, x, o,
o, o, o, x, x, x,
x, x, o, o, x, x,
o, x, x, x, x, o,
o, o, o, o, o, o, 
/* T */
x, x, x, x, x, x,
o, o, x, x, o, o,
o, o, x, x, o, o,
o, o, x, x, o, o,
o, o, x, x, o, o,
o, o, x, x, o, o,
o, o, x, x, o, o,
o, o, o, o, o, o, 
/* U */
x, x, o, o, x, x,
x, x, o, o, x, x,
x, x, o, o, x, x,
x, x, o, o, x, x,
x, x, o, o, x, x,
x, x, o, o, x, x,
o, x, x, x, x, o,
o, o, o, o, o, o, 
/* V */
x, x, o, o, o, x, x,
x, x, o, o, o, x, x,
x, x, o, o, o, x, x,
o, x, x, o, x, x, o,
o, x, x, o, x, x, o,
o, o, x, x, x, o, o,
o, o, x, x, x, o, o,
o, o, o, o, o, o, o, 
/* W */
x, x, o, o, o, o, x, x,
x, x, o, o, o, o, x, x,
x, x, o, o, o, o, x, x,
x, x, o, x, x, o, x, x,
x, x, o, x, x, o, x, x,
x, x, x, x, x, x, x, x,
o, x, x, o, o, x, x, o,
o, o, o, o, o, o, o, o, 
/* X */
x, x, o, x, x,
x, x, o, x, x,
x, x, x, x, x,
o, x, x, x, o,
x, x, x, x, x,
x, x, o, x, x,
x, x, o, x, x,
o, o, o, o, o, 
/* Y */
x, x, o, o, x, x,
x, x, o, o, x, x,
x, x, x, x, x, x,
o, x, x, x, x, o,
o, o, x, x, o, o,
o, o, x, x, o, o,
o, o, x, x, o, o,
o, o, o, o, o, o, 
/* Z */
x, x, x, x, x, x,
o, o, o, x, x, x,
o, o, x, x, x, o,
o, x, x, x, x, o,
o, x, x, x, o, o,
x, x, x, o, o, o,
x, x, x, x, x, x,
o, o, o, o, o, o, 
/* [ */
x, x, x,
x, x, o,
x, x, o,
x, x, o,
x, x, o,
x, x, o,
x, x, x,
o, o, o, 
/* \ */
x, o, o, o,
x, x, o, o,
x, x, o, o,
o, x, x, o,
o, o, x, x,
o, o, x, x,
o, o, o, x,
o, o, o, o, 
/* ] */
x, x, x,
o, x, x,
o, x, x,
o, x, x,
o, x, x,
o, x, x,
x, x, x,
o, o, o, 
/* ^ */
o, o, x, o, o,
o, x, x, x, o,
x, x, o, x, x,
o, o, o, o, o,
o, o, o, o, o,
o, o, o, o, o,
o, o, o, o, o,
o, o, o, o, o, 
/* _ */
o, o, o, o, o,
o, o, o, o, o,
o, o, o, o, o,
o, o, o, o, o,
o, o, o, o, o,
o, o, o, o, o,
x, x, x, x, x,
o, o, o, o, o, 
/* ` */
x, o,
x, x,
o, x,
o, o,
o, o,
o, o,
o, o,
o, o, 
/* a */
o, o, o, o, o,
o, o, o, o, o,
o, x, x, x, o,
o, o, o, x, x,
o, x, x, x, x,
x, x, o, x, x,
o, x, x, x, x,
o, o, o, o, o, 
/* b */
x, x, o, o, o,
x, x, o, o, o,
x, x, x, x, o,
x, x, o, x, x,
x, x, o, x, x,
x, x, o, x, x,
x, x, x, x, o,
o, o, o, o, o, 
/* c */
o, o, o, o,
o, o, o, o,
o, x, x, x,
x, x, o, o,
x, x, o, o,
x, x, o, o,
o, x, x, x,
o, o, o, o, 
/* d */
o, o, o, x, x,
o, o, o, x, x,
o, x, x, x, x,
x, x, o, x, x,
x, x, o, x, x,
x, x, o, x, x,
o, x, x, x, x,
o, o, o, o, o, 
/* e */
o, o, o, o, o,
o, o, o, o, o,
o, x, x, x, o,
x, x, o, o, x,
x, x, x, x, x,
x, x, o, o, o,
o, x, x, x, x,
o, o, o, o, o, 
/* f */
o, o, x, x,
o, x, x, o,
o, x, x, o,
x, x, x, x,
o, x, x, o,
o, x, x, o,
o, x, x, o,
o, o, o, o, 
/* g */
o, o, o, o, o,
o, o, o, o, o,
o, x, x, x, x,
x, x, o, x, x,
x, x, o, x, x,
o, x, x, x, x,
o, o, o, x, x,
x, x, x, x, o, 
/* h */
x, x, o, o, o,
x, x, o, o, o,
x, x, x, x, o,
x, x, o, x, x,
x, x, o, x, x,
x, x, o, x, x,
x, x, o, x, x,
o, o, o, o, o, 
/* i */
x, x,
o, o,
x, x,
x, x,
x, x,
x, x,
x, x,
o, o, 
/* j */
x, x,
o, o,
x, x,
x, x,
x, x,
x, x,
x, x,
x, o, 
/* k */
x, x, o, o, o,
x, x, o, o, o,
x, x, o, x, x,
x, x, x, x, o,
x, x, x, o, o,
x, x, x, x, o,
x, x, o, x, x,
o, o, o, o, o, 
/* l */
x, x, o,
x, x, o,
x, x, o,
x, x, o,
x, x, o,
x, x, o,
o, x, x,
o, o, o, 
/* m */
o, o, o, o, o, o, o, o,
o, o, o, o, o, o, o, o,
x, x, x, x, o, x, x, o,
x, x, o, x, x, o, x, x,
x, x, o, x, x, o, x, x,
x, x, o, x, x, o, x, x,
x, x, o, x, x, o, x, x,
o, o, o, o, o, o, o, o, 
/* n */
o, o, o, o, o,
o, o, o, o, o,
x, x, x, x, o,
x, x, o, x, x,
x, x, o, x, x,
x, x, o, x, x,
x, x, o, x, x,
o, o, o, o, o, 
/* o */
o, o, o, o, o,
o, o, o, o, o,
o, x, x, x, o,
x, x, o, x, x,
x, x, o, x, x,
x, x, o, x, x,
o, x, x, x, o,
o, o, o, o, o, 
/* p */
o, o, o, o, o,
o, o, o, o, o,
x, x, x, x, o,
x, x, o, x, x,
x, x, o, x, x,
x, x, x, x, o,
x, x, o, o, o,
x, x, o, o, o, 
/* q */
o, o, o, o, o,
o, o, o, o, o,
o, x, x, x, x,
x, x, o, x, x,
x, x, o, x, x,
o, x, x, x, x,
o, o, o, x, x,
o, o, o, x, x, 
/* r */
o, o, o, o,
o, o, o, o,
x, x, o, x,
x, x, x, o,
x, x, o, o,
x, x, o, o,
x, x, o, o,
o, o, o, o, 
/* s */
o, o, o, o, o,
o, o, o, o, o,
o, x, x, x, x,
x, x, o, o, o,
o, x, x, x, o,
o, o, o, x, x,
x, x, x, x, o,
o, o, o, o, o, 
/* t */
o, x, x, o,
o, x, x, o,
x, x, x, x,
o, x, x, o,
o, x, x, o,
o, x, x, o,
o, o, x, x,
o, o, o, o, 
/* u */
o, o, o, o, o,
o, o, o, o, o,
x, x, o, x, x,
x, x, o, x, x,
x, x, o, x, x,
x, x, o, x, x,
o, x, x, x, o,
o, o, o, o, o, 
/* v */
o, o, o, o, o,
o, o, o, o, o,
x, x, o, x, x,
x, x, o, x, x,
x, x, o, x, x,
o, x, x, x, o,
o, o, x, o, o,
o, o, o, o, o, 
/* w */
o, o, o, o, o, o, o,
o, o, o, o, o, o, o,
x, x, o, o, o, x, x,
x, x, o, o, o, x, x,
x, x, o, x, o, x, x,
x, x, o, x, o, x, x,
o, x, x, o, x, x, o,
o, o, o, o, o, o, o, 
/* x */
o, o, o, o, o,
o, o, o, o, o,
x, x, o, x, x,
o, x, x, x, o,
o, o, x, o, o,
o, x, x, x, o,
x, x, o, x, x,
o, o, o, o, o, 
/* y */
o, o, o, o, o,
o, o, o, o, o,
x, x, o, x, x,
x, x, o, x, x,
x, x, o, x, x,
o, x, x, x, x,
o, o, o, x, x,
x, x, x, x, o, 
/* z */
o, o, o, o, o,
o, o, o, o, o,
x, x, x, x, x,
o, o, o, x, x,
o, o, x, x, o,
o, x, x, o, o,
x, x, x, x, x,
o, o, o, o, o, 
/* { */
o, o, x, x,
o, x, x, o,
o, x, x, o,
x, x, o, o,
o, x, x, o,
o, x, x, o,
o, o, x, x,
o, o, o, o, 
/* | */
x,
x,
x,
x,
x,
x,
x,
x, 
/* } */
x, x, o, o,
o, x, x, o,
o, x, x, o,
o, o, x, x,
o, x, x, o,
o, x, x, o,
x, x, o, o,
o, o, o, o, 
/* ~ */
o, o, o, o, o, o,
o, o, o, o, o, o,
o, o, o, o, o, o,
o, x, x, o, x, x,
x, x, o, x, x, o,
o, o, o, o, o, o,
o, o, o, o, o, o,
o, o, o, o, o, o
};
#undef x
#undef o

const int Octafont_bold8::jumps[] = {
   -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
/* */    0,    32,    48,    88,   152,   216,   296,   344, 
/*(*/  360,   392,   424,   480,   528,   544,   568,   584, 
/*0*/  616,   664,   688,   736,   776,   824,   864,   904, 
/*8*/  952,  1000,  1040,  1056,  1072,  1104,  1136,  1168, 
/*@*/ 1208,  1272,  1328,  1376,  1416,  1456,  1496,  1536, 
/*H*/ 1576,  1624,  1640,  1680,  1728,  1768,  1824,  1880, 
/*P*/ 1928,  1976,  2032,  2080,  2128,  2176,  2224,  2280, 
/*X*/ 2344,  2384,  2432,  2480,  2504,  2536,  2560,  2600, 
/*`*/ 2640,  2656,  2696,  2736,  2768,  2808,  2848,  2880, 
/*h*/ 2920,  2960,  2976,  2992,  3032,  3056,  3120,  3160, 
/*p*/ 3200,  3240,  3280,  3312,  3352,  3384,  3424,  3464, 
/*x*/ 3520,  3560,  3600,  3640,  3672,  3680,  3712,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1
};

const int Octafont_bold8::widths[] = {
-1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
/* */ 4,  2,  5,  8,  8, 10,  6,  2, 
/*(*/ 4,  4,  7,  6,  2,  3,  2,  4, 
/*0*/ 6,  3,  6,  5,  6,  5,  5,  6, 
/*8*/ 6,  5,  2,  2,  4,  4,  4,  5, 
/*@*/ 8,  7,  6,  5,  5,  5,  5,  5, 
/*H*/ 6,  2,  5,  6,  5,  7,  7,  6, 
/*P*/ 6,  7,  6,  6,  6,  6,  7,  8, 
/*X*/ 5,  6,  6,  3,  4,  3,  5,  5, 
/*`*/ 2,  5,  5,  4,  5,  5,  4,  5, 
/*h*/ 5,  2,  2,  5,  3,  8,  5,  5, 
/*p*/ 5,  5,  4,  5,  4,  5,  5,  7, 
/*x*/ 5,  5,  5,  4,  1,  4,  6, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1
};
#endif //OCTAFONT_BOLD8_H_
