
#ifndef OCTAFONT7_H_
#define OCTAFONT7_H_

#include "pixelfont.h"

class Octafont7: public PixelFont {

private:
    static const bool chars[];
    static const int jumps[];
    static const int widths[];
    static const int height = 7;

    const bool *get_chars() override {
        return chars;
    }

    const int* get_jumps() override {
        return jumps;
    }

    const int* get_widths() override {
        return widths;
    }
    
    int get_font_height() override {
        return height;
    }
};

#define x true
#define o false
const bool Octafont7::chars[] = {
/*   */
o, o, o, o,
o, o, o, o,
o, o, o, o,
o, o, o, o,
o, o, o, o,
o, o, o, o,
o, o, o, o, 
/* ! */
x,
x,
x,
x,
o,
x,
o, 
/* " */
x, o, x,
o, o, o,
o, o, o,
o, o, o,
o, o, o,
o, o, o,
o, o, o, 
/* # */
o, x, o, o, x, o,
x, x, x, x, x, x,
o, x, o, o, x, o,
o, x, o, o, x, o,
x, x, x, x, x, x,
o, x, o, o, x, o,
o, o, o, o, o, o, 
/* $ */
o, o, x, o, o,
o, x, x, x, x,
x, o, x, o, o,
o, x, x, x, o,
o, o, x, o, x,
x, x, x, x, o,
o, o, o, o, o, 
/* % */
o, x, o, o, o, o, x, o,
x, o, x, o, o, x, o, o,
o, x, o, o, x, o, o, o,
o, o, o, x, o, o, x, o,
o, o, x, o, o, x, o, x,
o, x, o, o, o, o, x, o,
o, o, o, o, o, o, o, o, 
/* & */
o, x, x, o, o,
x, o, o, x, o,
o, x, o, x, o,
x, o, x, o, o,
x, o, o, x, o,
o, x, x, o, x,
o, o, o, o, o, 
/* ' */
x,
o,
o,
o,
o,
o,
o, 
/* ( */
o, o, x,
o, x, o,
x, o, o,
x, o, o,
o, x, o,
o, o, x,
o, o, o, 
/* ) */
x, o, o,
o, x, o,
o, o, x,
o, o, x,
o, x, o,
x, o, o,
o, o, o, 
/* * */
o, o, x, o, o,
x, o, x, o, x,
o, x, x, x, o,
x, o, x, o, x,
o, o, x, o, o,
o, o, o, o, o,
o, o, o, o, o, 
/* + */
o, o, o,
o, x, o,
x, x, x,
o, x, o,
o, o, o,
o, o, o,
o, o, o, 
/* , */
o, o,
o, o,
o, o,
o, o,
o, x,
x, o,
o, o, 
/* - */
o, o, o,
o, o, o,
x, x, x,
o, o, o,
o, o, o,
o, o, o,
o, o, o, 
/* . */
o,
o,
o,
o,
o,
x,
o, 
/* / */
x,
o,
o,
o,
o,
o,
o, 
/* 0 */
o, x, x, o,
x, o, o, x,
x, o, o, x,
x, o, x, x,
x, x, o, x,
o, x, x, o,
o, o, o, o, 
/* 1 */
o, x,
x, x,
o, x,
o, x,
o, x,
o, x,
o, o, 
/* 2 */
x, x, x, x,
o, o, o, x,
o, o, o, x,
x, x, x, x,
x, o, o, o,
x, x, x, x,
o, o, o, o, 
/* 3 */
x, x, x, x,
o, o, o, x,
o, o, o, x,
o, x, x, x,
o, o, o, x,
x, x, x, x,
o, o, o, o, 
/* 4 */
o, o, o, x, o,
o, o, x, o, o,
o, x, o, o, o,
x, o, o, x, o,
x, x, x, x, x,
o, o, o, x, o,
o, o, o, o, o, 
/* 5 */
x, x, x, x,
x, o, o, o,
x, o, o, o,
x, x, x, x,
o, o, o, x,
x, x, x, x,
o, o, o, o, 
/* 6 */
x, x, x, x,
x, o, o, o,
x, o, o, o,
x, x, x, o,
x, o, o, x,
x, x, x, x,
o, o, o, o, 
/* 7 */
x, x, x, x, x,
o, o, o, o, x,
o, o, o, x, o,
o, o, x, o, o,
o, x, o, o, o,
o, x, o, o, o,
o, o, o, o, o, 
/* 8 */
x, x, x, x,
x, o, o, x,
x, o, o, x,
x, x, x, x,
x, o, o, x,
x, x, x, x,
o, o, o, o, 
/* 9 */
x, x, x, x,
x, o, o, x,
x, o, o, x,
x, x, x, x,
o, o, o, x,
x, x, x, x,
o, o, o, o, 
/* : */
o,
x,
o,
o,
x,
o,
o, 
/* ; */
o, o,
o, x,
o, o,
o, o,
o, o,
o, x,
x, o, 
/* < */
o, o, o, o,
o, o, o, x,
o, x, x, o,
x, o, o, o,
o, x, x, o,
o, o, o, x,
o, o, o, o, 
/* = */
o, o, o, o,
o, o, o, o,
x, x, x, x,
o, o, o, o,
x, x, x, x,
o, o, o, o,
o, o, o, o, 
/* > */
o, o, o, o,
x, o, o, o,
o, x, x, o,
o, o, o, x,
o, x, x, o,
x, o, o, o,
o, o, o, o, 
/* ? */
x, x, x, x,
x, o, o, x,
o, o, o, x,
o, o, x, o,
o, o, o, o,
o, o, x, o,
o, o, o, o, 
/* @ */
o, o, x, x, x, o,
o, x, o, o, o, x,
x, o, o, x, x, x,
x, o, x, o, o, x,
x, o, o, x, x, x,
o, x, o, o, o, o,
o, o, x, x, x, o, 
/* A */
o, x, x, x, o,
x, o, o, o, x,
x, o, o, o, x,
x, o, o, o, x,
x, x, x, x, x,
x, o, o, o, x,
o, o, o, o, o, 
/* B */
x, x, x, o,
x, o, o, x,
x, o, o, x,
x, x, x, o,
x, o, o, x,
x, x, x, x,
o, o, o, o, 
/* C */
o, x, x, x,
x, o, o, o,
x, o, o, o,
x, o, o, o,
x, o, o, o,
o, x, x, x,
o, o, o, o, 
/* D */
x, x, x, o,
x, o, o, x,
x, o, o, x,
x, o, o, x,
x, o, o, x,
x, x, x, o,
o, o, o, o, 
/* E */
x, x, x, x,
x, o, o, o,
x, o, o, o,
x, x, x, o,
x, o, o, o,
x, x, x, x,
o, o, o, o, 
/* F */
x, x, x, x,
x, o, o, o,
x, o, o, o,
x, x, x, o,
x, o, o, o,
x, o, o, o,
o, o, o, o, 
/* G */
o, x, x, o,
x, o, o, o,
x, o, x, o,
x, o, o, x,
x, o, o, x,
x, x, x, o,
o, o, o, o, 
/* H */
x, o, o, x,
x, o, o, x,
x, o, o, x,
x, x, x, x,
x, o, o, x,
x, o, o, x,
o, o, o, o, 
/* I */
x,
x,
x,
x,
x,
x,
o, 
/* J */
o, o, o, x,
o, o, o, x,
o, o, o, x,
o, o, o, x,
x, o, o, x,
o, x, x, o,
o, o, o, o, 
/* K */
x, o, o, x, o,
x, o, o, x, o,
x, o, x, o, o,
x, x, o, o, o,
x, o, x, o, o,
x, o, o, x, o,
o, o, o, o, o, 
/* L */
x, o, o, o,
x, o, o, o,
x, o, o, o,
x, o, o, o,
x, o, o, o,
x, x, x, x,
o, o, o, o, 
/* M */
x, o, o, o, x,
x, x, o, x, x,
x, o, x, o, x,
x, o, o, o, x,
x, o, o, o, x,
x, o, o, o, x,
o, o, o, o, o, 
/* N */
x, o, o, o, x,
x, o, o, o, x,
x, x, o, o, x,
x, o, x, o, x,
x, o, o, x, x,
x, o, o, o, x,
o, o, o, o, o, 
/* O */
o, x, x, o,
x, o, o, x,
x, o, o, x,
x, o, o, x,
x, o, o, x,
o, x, x, o,
o, o, o, o, 
/* P */
x, x, x, o,
x, o, o, x,
x, o, o, x,
x, x, x, o,
x, o, o, o,
x, o, o, o,
o, o, o, o, 
/* Q */
o, x, x, x, o, o,
x, o, o, o, x, o,
x, o, o, o, x, o,
x, o, o, o, x, o,
x, o, o, o, x, o,
o, x, x, x, o, o,
o, o, o, o, x, x, 
/* R */
x, x, o,
x, o, x,
x, o, x,
x, o, x,
x, x, o,
x, o, x,
o, o, o, 
/* S */
o, x, x, o,
x, o, o, x,
x, o, o, o,
o, x, x, o,
o, o, o, x,
x, x, x, o,
o, o, o, o, 
/* T */
x, x, x, x, x,
o, o, x, o, o,
o, o, x, o, o,
o, o, x, o, o,
o, o, x, o, o,
o, o, x, o, o,
o, o, o, o, o, 
/* U */
x, o, o, x,
x, o, o, x,
x, o, o, x,
x, o, o, x,
x, o, o, x,
o, x, x, o,
o, o, o, o, 
/* V */
x, o, o, o, x,
x, o, o, o, x,
x, o, o, o, x,
x, o, o, o, x,
o, x, o, x, x,
o, o, x, o, o,
o, o, o, o, o, 
/* W */
x, o, o, o, o, o, x,
x, o, o, o, o, o, x,
x, o, o, o, o, o, x,
x, o, o, x, o, o, x,
x, o, x, o, x, o, x,
o, x, o, o, o, x, o,
o, o, o, o, o, o, o, 
/* X */
x, o, o, o, x,
x, o, o, o, x,
o, x, o, x, o,
o, o, x, o, o,
o, x, o, x, o,
x, o, o, o, x,
o, o, o, o, o, 
/* Y */
x, o, o, o, x,
x, o, o, o, x,
o, x, o, x, o,
o, x, o, x, o,
o, o, x, o, o,
o, o, x, o, o,
o, o, o, o, o, 
/* Z */
x, x, x, x, x,
o, o, o, o, x,
o, o, o, x, o,
o, o, x, o, o,
o, x, o, o, o,
x, x, x, x, x,
o, o, o, o, o, 
/* [ */
x, x,
x, o,
x, o,
x, o,
x, o,
x, x,
o, o, 
/* \ */
x, o, o, o, o,
o, x, o, o, o,
o, x, o, o, o,
o, o, x, o, o,
o, o, x, o, o,
o, o, o, x, o,
o, o, o, o, o, 
/* ] */
x, x,
o, x,
o, x,
o, x,
o, x,
x, x,
o, o, 
/* ^ */
o, x, o,
x, o, x,
o, o, o,
o, o, o,
o, o, o,
o, o, o,
o, o, o, 
/* _ */
o, o, o, o, o,
o, o, o, o, o,
o, o, o, o, o,
o, o, o, o, o,
o, o, o, o, o,
x, x, x, x, x,
o, o, o, o, o, 
/* ` */
x, o,
o, x,
o, o,
o, o,
o, o,
o, o,
o, o, 
/* a */
o, o, o, o,
o, x, x, o,
o, o, o, x,
o, x, x, x,
x, o, o, x,
o, x, x, x,
o, o, o, o, 
/* b */
x, o, o, o,
x, o, o, o,
x, x, x, o,
x, o, o, x,
x, o, o, x,
o, x, x, o,
o, o, o, o, 
/* c */
o, o, o, o,
o, o, o, o,
o, x, x, x,
x, o, o, o,
x, o, o, o,
o, x, x, x,
o, o, o, o, 
/* d */
o, o, o, x,
o, o, o, x,
o, x, x, x,
x, o, o, x,
x, o, o, x,
o, x, x, o,
o, o, o, o, 
/* e */
o, o, o, o,
o, x, x, o,
x, o, o, x,
x, x, x, x,
x, o, o, o,
o, x, x, o,
o, o, o, o, 
/* f */
o, o, x,
o, x, o,
o, x, o,
x, x, x,
o, x, o,
o, x, o,
o, o, o, 
/* g */
o, o, o, o,
o, x, x, x,
x, o, o, x,
x, o, o, x,
o, x, x, x,
o, o, o, x,
x, x, x, x, 
/* h */
x, o, o, o,
x, o, o, o,
x, x, x, o,
x, o, o, x,
x, o, o, x,
x, o, o, x,
o, o, o, o, 
/* i */
x,
o,
x,
x,
x,
x,
o, 
/* j */
o, x,
o, o,
o, x,
o, x,
o, x,
o, x,
x, o, 
/* k */
x, o, o,
x, o, o,
x, o, o,
x, o, x,
x, x, o,
x, o, x,
o, o, o, 
/* l */
x, o,
x, o,
x, o,
x, o,
x, o,
o, x,
o, o, 
/* m */
o, o, o, o, o, o, o,
o, o, o, o, o, o, o,
x, x, x, o, x, x, o,
x, o, o, x, o, o, x,
x, o, o, x, o, o, x,
x, o, o, x, o, o, x,
o, o, o, o, o, o, o, 
/* n */
o, o, o, o,
o, o, o, o,
x, x, x, o,
x, o, o, x,
x, o, o, x,
x, o, o, x,
o, o, o, o, 
/* o */
o, o, o, o,
o, o, o, o,
o, x, x, o,
x, o, o, x,
x, o, o, x,
o, x, x, o,
o, o, o, o, 
/* p */
o, o, o, o,
o, o, o, o,
x, x, x, o,
x, o, o, x,
x, o, o, x,
x, x, x, o,
x, o, o, o, 
/* q */
o, o, o, o,
o, o, o, o,
o, x, x, x,
x, o, o, x,
x, o, o, x,
o, x, x, x,
o, o, o, x, 
/* r */
o, o, o,
o, o, o,
x, o, x,
x, x, o,
x, o, o,
x, o, o,
o, o, o, 
/* s */
o, o, o, o,
o, o, o, o,
o, x, x, x,
o, x, o, o,
o, o, x, o,
x, x, x, o,
o, o, o, o, 
/* t */
o, x, o,
o, x, o,
x, x, x,
o, x, o,
o, x, o,
o, o, x,
o, o, o, 
/* u */
o, o, o, o,
o, o, o, o,
x, o, o, x,
x, o, o, x,
x, o, o, x,
o, x, x, o,
o, o, o, o, 
/* v */
o, o, o, o, o,
o, o, o, o, o,
x, o, o, o, x,
x, o, o, o, x,
o, x, o, x, o,
o, o, x, o, o,
o, o, o, o, o, 
/* w */
o, o, o, o, o,
o, o, o, o, o,
x, o, o, o, x,
x, o, o, o, x,
x, o, x, o, x,
o, x, x, x, o,
o, o, o, o, o, 
/* x */
o, o, o, o,
o, o, o, o,
x, o, o, x,
o, x, x, o,
o, x, x, o,
x, o, o, x,
o, o, o, o, 
/* y */
o, o, o, o,
o, o, o, o,
x, o, o, x,
x, o, o, x,
x, x, x, x,
o, o, o, x,
x, x, x, x, 
/* z */
o, o, o, o,
o, o, o, o,
x, x, x, x,
o, o, x, o,
o, x, o, o,
x, x, x, x,
o, o, o, o, 
/* { */
o, o, x,
o, x, o,
o, x, o,
x, o, o,
o, x, o,
o, o, x,
o, o, o, 
/* | */
x,
x,
x,
x,
x,
x,
x, 
/* } */
x, o, o,
o, x, o,
o, x, o,
o, o, x,
o, x, o,
x, o, o,
o, o, o, 
/* ~ */
o, o, o, o,
o, o, o, o,
o, x, o, x,
x, o, x, o,
o, o, o, o,
o, o, o, o,
o, o, o, o
};
#undef x
#undef o

const int Octafont7::jumps[] = {
   -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
/* */    0,    28,    35,    56,    98,   133,   189,   224, 
/*(*/  231,   252,   273,   308,   329,   343,   364,   371, 
/*0*/  378,   406,   420,   448,   476,   511,   539,   567, 
/*8*/  602,   630,   658,   665,   679,   707,   735,   763, 
/*@*/  791,   833,   868,   896,   924,   952,   980,  1008, 
/*H*/ 1036,  1064,  1071,  1099,  1134,  1162,  1197,  1232, 
/*P*/ 1260,  1288,  1330,  1351,  1379,  1414,  1442,  1477, 
/*X*/ 1526,  1561,  1596,  1631,  1645,  1680,  1694,  1715, 
/*`*/ 1750,  1764,  1792,  1820,  1848,  1876,  1904,  1925, 
/*h*/ 1953,  1981,  1988,  2002,  2023,  2037,  2086,  2114, 
/*p*/ 2142,  2170,  2198,  2219,  2247,  2268,  2296,  2331, 
/*x*/ 2366,  2394,  2422,  2450,  2471,  2478,  2499,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1, 
       -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1
};

const int Octafont7::widths[] = {
-1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
/* */ 4,  1,  3,  6,  5,  8,  5,  1, 
/*(*/ 3,  3,  5,  3,  2,  3,  1,  1, 
/*0*/ 4,  2,  4,  4,  5,  4,  4,  5, 
/*8*/ 4,  4,  1,  2,  4,  4,  4,  4, 
/*@*/ 6,  5,  4,  4,  4,  4,  4,  4, 
/*H*/ 4,  1,  4,  5,  4,  5,  5,  4, 
/*P*/ 4,  6,  3,  4,  5,  4,  5,  7, 
/*X*/ 5,  5,  5,  2,  5,  2,  3,  5, 
/*`*/ 2,  4,  4,  4,  4,  4,  3,  4, 
/*h*/ 4,  1,  2,  3,  2,  7,  4,  4, 
/*p*/ 4,  4,  3,  4,  3,  4,  5,  5, 
/*x*/ 4,  4,  4,  3,  1,  3,  4, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1
};
#endif //OCTAFONT7_H_
